return {
  ["copper-display"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.copper-display"),
  ["copper-display-medium"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.copper-display-medium"),
  ["copper-display-small"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.copper-display-small"),
  ["copper-display-xl"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.copper-display-xl"),
  ["display-panel"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.display-panel"),
  ["iron-display"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.iron-display"),
  ["iron-display-medium"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.iron-display-medium"),
  ["iron-display-small"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.iron-display-small"),
  ["iron-display-xl"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.iron-display-xl"),
  ["steel-display"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.steel-display"),
  ["steel-display-medium"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.steel-display-medium"),
  ["steel-display-small"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.steel-display-small"),
  ["steel-display-xl"] = require("___KHAOSDATA___.prototypes.data-raw.display-panel.steel-display-xl"),
}
