return {
  ["arithmetic-combinator"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.arithmetic-combinator"),
  ["belt-arithmetic-combinator"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.belt-arithmetic-combinator"),
  ["compaktcircuit-ac"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.compaktcircuit-ac"),
  ["cybersyn-combinator"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.cybersyn-combinator"),
  ["hps__fc-filter-combinator"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.hps__fc-filter-combinator"),
  ["hps__fc-filter-combinator-ac"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.hps__fc-filter-combinator-ac"),
  ["hps__fc-filter-combinator-debug-ac"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.hps__fc-filter-combinator-debug-ac"),
  ["hps__fc-filter-combinator-packed"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.hps__fc-filter-combinator-packed"),
  ["hps__sc-stack-combinator-redux"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.hps__sc-stack-combinator-redux"),
  ["hps__sc-stack-combinator-redux-packed"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.hps__sc-stack-combinator-redux-packed"),
  ["microcontroller"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.microcontroller"),
  ["recipe-combinator-component-arithmetic-combinator"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.recipe-combinator-component-arithmetic-combinator"),
  ["recipe-combinator-main"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.recipe-combinator-main"),
  ["signal-diode-combinator"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.signal-diode-combinator"),
  ["signal-diode-combinator-packed"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.signal-diode-combinator-packed"),
  ["stc-typed-probe"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.stc-typed-probe"),
  ["stc2-buffer-probe"] = require("___KHAOSDATA___.prototypes.data-raw.arithmetic-combinator.stc2-buffer-probe"),
}
