return {
  ["copy"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.copy"),
  ["cut"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.cut"),
  ["cybersyn-toggle-gui"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.cybersyn-toggle-gui"),
  ["give-artillery-targeting-remote"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-artillery-targeting-remote"),
  ["give-blueprint"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-blueprint"),
  ["give-blueprint-book"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-blueprint-book"),
  ["give-copper-wire"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-copper-wire"),
  ["give-deconstruction-planner"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-deconstruction-planner"),
  ["give-discharge-defense-remote"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-discharge-defense-remote"),
  ["give-green-wire"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-green-wire"),
  ["give-red-wire"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-red-wire"),
  ["give-spidertron-remote"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-spidertron-remote"),
  ["give-upgrade-planner"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.give-upgrade-planner"),
  ["import-string"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.import-string"),
  ["paste"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.paste"),
  ["qf-fabricator-enable"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.qf-fabricator-enable"),
  ["qf-fabricator-gui"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.qf-fabricator-gui"),
  ["redo"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.redo"),
  ["stc2-open-overview"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.stc2-open-overview"),
  ["toggle-alt-mode"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.toggle-alt-mode"),
  ["toggle-equipment-movement-bonus"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.toggle-equipment-movement-bonus"),
  ["toggle-personal-roboport"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.toggle-personal-roboport"),
  ["toggle-tall-entity-visibility"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.toggle-tall-entity-visibility"),
  ["undo"] = require("___KHAOSDATA___.prototypes.data-raw.shortcut.undo"),
}
