return {
  ["alert-scanner-activity-ghost-inner"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.alert-scanner-activity-ghost-inner"),
  ["alert-scanner-network-access"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.alert-scanner-network-access"),
  ["compaktcircuit-device"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-device"),
  ["compaktcircuit-display"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-display"),
  ["compaktcircuit-iopoint"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-iopoint"),
  ["compaktcircuit-lamp1"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-lamp1"),
  ["compaktcircuit-lamp2"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-lamp2"),
  ["compaktcircuit-lamp3"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-lamp3"),
  ["compaktcircuit-lamp4"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-lamp4"),
  ["compaktcircuit-lamp5"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-lamp5"),
  ["compaktcircuit-lamp6"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-lamp6"),
  ["compaktcircuit-lamp7"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-lamp7"),
  ["compaktcircuit-lamp8"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-lamp8"),
  ["compaktcircuit-packed-display"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.compaktcircuit-packed-display"),
  ["hps__fo-led"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.hps__fo-led"),
  ["hps__fo-power-interface"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.hps__fo-power-interface"),
  ["logistic-train-stop-input"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.logistic-train-stop-input"),
  ["power-combinator-meter-satisfaction"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.power-combinator-meter-satisfaction"),
  ["signal-lamp"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.signal-lamp"),
  ["small-lamp"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.small-lamp"),
  ["stc2-power"] = require("___KHAOSDATA___.prototypes.data-raw.lamp.stc2-power"),
}
