return {
  ["factory-linked-express-loader"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-express-loader"),
  ["factory-linked-express-splitter"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-express-splitter"),
  ["factory-linked-express-transport-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-express-transport-belt"),
  ["factory-linked-express-underground-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-express-underground-belt"),
  ["factory-linked-fast-loader"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-fast-loader"),
  ["factory-linked-fast-splitter"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-fast-splitter"),
  ["factory-linked-fast-transport-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-fast-transport-belt"),
  ["factory-linked-fast-underground-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-fast-underground-belt"),
  ["factory-linked-lane-splitter"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-lane-splitter"),
  ["factory-linked-linked-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-linked-belt"),
  ["factory-linked-loader"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-loader"),
  ["factory-linked-loader-1x1"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-loader-1x1"),
  ["factory-linked-splitter"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-splitter"),
  ["factory-linked-transport-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-transport-belt"),
  ["factory-linked-turbo-loader"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-turbo-loader"),
  ["factory-linked-turbo-splitter"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-turbo-splitter"),
  ["factory-linked-turbo-transport-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-turbo-transport-belt"),
  ["factory-linked-turbo-underground-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-turbo-underground-belt"),
  ["factory-linked-underground-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.factory-linked-underground-belt"),
  ["linked-belt"] = require("___KHAOSDATA___.prototypes.data-raw.linked-belt.linked-belt"),
}
